-- ============================================================
-- SECURITY HARDENING MIGRATION
-- Run this ONCE in Supabase SQL Editor
-- ============================================================

-- Enable RLS on all critical tables (safe to run multiple times)
ALTER TABLE IF EXISTS profiles         ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tenants          ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mobiles          ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS accessories      ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS customers        ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS suppliers        ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sales            ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sale_items       ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS purchases        ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS purchase_items   ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS returns          ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS return_items     ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS imei_records     ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS finance_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payments         ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS expenses         ENABLE ROW LEVEL SECURITY;
