"use client"
import React, { createContext, useContext, useState, useEffect, useCallback } from "react"

export type Language = "en" | "ur"

// ---------------------------------------------------------------------------
// Translations dictionary
// Rules:
//  - English = default, clear plain text (no Dr/Cr jargon)
//  - Urdu = Pakistani shopkeeper Urdu (not formal/literary), written in Nastaliq script
//  - Data values (IMEI, prices, names) are NEVER translated — only labels/buttons/placeholders
// ---------------------------------------------------------------------------
const translations = {
  // ── Sidebar sections ──────────────────────────────────────────────────────
  "nav.section.MAIN":         { en: "MAIN",         ur: "مین" },
  "nav.section.INVENTORY":    { en: "INVENTORY",    ur: "اسٹاک" },
  "nav.section.TRANSACTIONS": { en: "TRANSACTIONS", ur: "لین دین" },
  "nav.section.PEOPLE":       { en: "PEOPLE",       ur: "افراد" },
  "nav.section.INSIGHTS":     { en: "INSIGHTS",     ur: "رپورٹس" },
  "nav.section.SYSTEM":       { en: "SYSTEM",       ur: "سسٹم" },

  // ── Sidebar nav items ─────────────────────────────────────────────────────
  "nav.Dashboard":          { en: "Dashboard",         ur: "ڈیش بورڈ" },
  "nav.Mobile Phones":      { en: "Mobile Phones",     ur: "موبائل فون" },
  "nav.Accessories":        { en: "Accessories",       ur: "اضافی سامان" },
  "nav.Stock Alerts":       { en: "Stock Alerts",      ur: "اسٹاک الرٹ" },
  "nav.Used Phones":        { en: "Used Phones",       ur: "پرانے فون" },
  "nav.Catalog":            { en: "Catalog",           ur: "کیٹالاگ" },
  "nav.Categories":         { en: "Categories",        ur: "اقسام" },
  "nav.Brands":             { en: "Brands",            ur: "برانڈز" },
  "nav.Models":             { en: "Models",            ur: "ماڈلز" },
  "nav.Colors":             { en: "Colors",            ur: "رنگ" },
  "nav.Storage":            { en: "Storage",           ur: "میموری" },
  "nav.RAM":                { en: "RAM",               ur: "ریم" },
  "nav.Sales":              { en: "Sales",             ur: "فروخت" },
  "nav.Purchases":          { en: "Purchases",         ur: "خریداری" },
  "nav.Returns":            { en: "Returns",           ur: "واپسی" },
  "nav.Sale Returns":       { en: "Sale Returns",      ur: "فروخت واپسی" },
  "nav.Purchase Returns":   { en: "Purchase Returns",  ur: "خریداری واپسی" },
  "nav.Rebate":             { en: "Rebate",            ur: "ریبیٹ" },
  "nav.Finance":            { en: "Finance",           ur: "مالیات" },
  "nav.Expenses":           { en: "Expenses",          ur: "اخراجات" },
  "nav.Ledger":             { en: "Ledger",            ur: "کھاتہ" },
  "nav.Customer Ledger":    { en: "Customer Ledger",   ur: "گاہک کھاتہ" },
  "nav.Supplier Ledger":    { en: "Supplier Ledger",   ur: "سپلائر کھاتہ" },
  "nav.Person Ledger":      { en: "Person Ledger",     ur: "ذاتی کھاتہ" },
  "nav.Suppliers":          { en: "Suppliers",         ur: "سپلائرز" },
  "nav.Customers":          { en: "Customers",         ur: "گاہک" },
  "nav.Persons":            { en: "Persons",           ur: "افراد" },
  "nav.Reports & Analytics":{ en: "Reports & Analytics", ur: "رپورٹس" },
  "nav.Staff":              { en: "Staff",             ur: "عملہ" },
  "nav.Audit Log":          { en: "Audit Log",         ur: "تبدیلی لاگ" },
  "nav.Settings":           { en: "Settings",          ur: "ترتیبات" },

  // ── Quick action buttons ──────────────────────────────────────────────────
  "action.New Sale":     { en: "New Sale",     ur: "نئی فروخت" },
  "action.New Purchase": { en: "New Purchase", ur: "نئی خریداری" },

  // ── Common buttons ────────────────────────────────────────────────────────
  "btn.Save":           { en: "Save Changes",   ur: "محفوظ کریں" },
  "btn.Saving":         { en: "Saving…",        ur: "محفوظ ہو رہا ہے…" },
  "btn.Cancel":         { en: "Cancel",         ur: "منسوخ" },
  "btn.Delete":         { en: "Delete",         ur: "حذف کریں" },
  "btn.Edit":           { en: "Edit",           ur: "ترمیم" },
  "btn.Add":            { en: "Add",            ur: "شامل کریں" },
  "btn.Search":         { en: "Search",         ur: "تلاش کریں" },
  "btn.Filter":         { en: "Filter",         ur: "فلٹر" },
  "btn.Export":         { en: "Export",         ur: "برآمد کریں" },
  "btn.Print":          { en: "Print",          ur: "پرنٹ کریں" },
  "btn.Close":          { en: "Close",          ur: "بند کریں" },
  "btn.Confirm":        { en: "Confirm",        ur: "تصدیق کریں" },
  "btn.Submit":         { en: "Submit",         ur: "جمع کروائیں" },
  "btn.Update":         { en: "Update",         ur: "اپ ڈیٹ کریں" },
  "btn.View":           { en: "View",           ur: "دیکھیں" },

  // ── Common labels ─────────────────────────────────────────────────────────
  "label.Name":         { en: "Name",           ur: "نام" },
  "label.Phone":        { en: "Phone",          ur: "فون نمبر" },
  "label.Email":        { en: "Email",          ur: "ای میل" },
  "label.Address":      { en: "Address",        ur: "پتہ" },
  "label.City":         { en: "City",           ur: "شہر" },
  "label.Date":         { en: "Date",           ur: "تاریخ" },
  "label.Notes":        { en: "Notes",          ur: "نوٹس" },
  "label.Status":       { en: "Status",         ur: "حیثیت" },
  "label.Amount":       { en: "Amount",         ur: "رقم" },
  "label.Price":        { en: "Price",          ur: "قیمت" },
  "label.Total":        { en: "Total",          ur: "کل رقم" },
  "label.Paid":         { en: "Paid",           ur: "ادا شدہ" },
  "label.Balance":      { en: "Balance",        ur: "بقایا" },
  "label.Brand":        { en: "Brand",          ur: "برانڈ" },
  "label.Model":        { en: "Model",          ur: "ماڈل" },
  "label.Color":        { en: "Color",          ur: "رنگ" },
  "label.Storage":      { en: "Storage",        ur: "میموری" },
  "label.Quantity":     { en: "Quantity",       ur: "تعداد" },
  "label.Category":     { en: "Category",       ur: "قسم" },
  "label.Supplier":     { en: "Supplier",       ur: "سپلائر" },
  "label.Customer":     { en: "Customer",       ur: "گاہک" },
  "label.IMEI":         { en: "IMEI",           ur: "آئی ایم ای آئی" },
  "label.CNIC":         { en: "CNIC",           ur: "شناختی کارڈ" },

  // ── Status values (also used by components/shared/status-badge.tsx) ────────
  "status.In Stock":      { en: "In Stock",       ur: "موجود ہے" },
  "status.Sold":          { en: "Sold",           ur: "فروخت ہو گیا" },
  "status.Under Repair":  { en: "Under Repair",   ur: "مرمت میں ہے" },
  "status.Active":        { en: "Active",         ur: "فعال" },
  "status.Inactive":      { en: "Inactive",       ur: "غیر فعال" },
  "status.Settled":       { en: "Settled",        ur: "حساب صاف" },
  "status.Pending":       { en: "Pending",        ur: "زیر التواء" },
  "status.Completed":     { en: "Completed",      ur: "مکمل" },
  "status.Refunded":      { en: "Refunded",       ur: "رقم واپس" },
  "status.Paid":          { en: "Paid",           ur: "ادا شدہ" },
  "status.Partial":       { en: "Partial",        ur: "کچھ ادا شدہ" },
  "status.Unpaid":        { en: "Unpaid",         ur: "ادائیگی باقی" },
  "status.Received":      { en: "Received",       ur: "موصول ہو گیا" },
  "status.Low Stock":     { en: "Low Stock",      ur: "اسٹاک کم ہے" },
  "status.Out of Stock":  { en: "Out of Stock",   ur: "اسٹاک ختم" },
  "status.Bronze":        { en: "Bronze",         ur: "برانز" },
  "status.Silver":        { en: "Silver",         ur: "سلور" },
  "status.Gold":          { en: "Gold",           ur: "گولڈ" },
  "status.Platinum":      { en: "Platinum",       ur: "پلاٹینم" },
  "status.New":           { en: "New",            ur: "نیا" },
  "status.Refurbished":   { en: "Refurbished",    ur: "مرمت شدہ" },
  "status.Used":          { en: "Used",           ur: "استعمال شدہ" },
  "status.Approved":      { en: "Approved",       ur: "منظور شدہ" },
  "status.Non-PTA":       { en: "Non-PTA",        ur: "نان-پی ٹی اے" },

  // ── Financial labels ──────────────────────────────────────────────────────
  "fin.Opening Balance":         { en: "Previous Balance",           ur: "پرانا بقایا" },
  "fin.Outstanding":             { en: "Outstanding",                ur: "باقی رقم" },
  "fin.Total Purchases":         { en: "Total Purchases",            ur: "کل خریداری" },
  "fin.Total Paid":              { en: "Total Paid",                 ur: "کل ادائیگی" },
  "fin.Net Balance":             { en: "Net Balance",                ur: "خالص بقایا" },
  "fin.We owe supplier":         { en: "We need to pay this supplier", ur: "ہمیں ابھی دینا ہے" },
  "fin.Supplier advance":        { en: "We paid extra (advance)",      ur: "ہم نے زیادہ دیا" },
  "fin.Customer owes":           { en: "Customer needs to pay",        ur: "گاہک کا بقایا ہے" },
  "fin.Customer advance":        { en: "Customer paid extra",          ur: "گاہک نے زیادہ دیا" },
  "fin.Account settled":         { en: "Account settled",              ur: "حساب صاف ہے" },
  "fin.They owe us":             { en: "They need to pay us",          ur: "انہیں دینا ہے" },
  "fin.We owe them":             { en: "We need to pay them",          ur: "ہمیں دینا ہے" },

  // ── Settings page ─────────────────────────────────────────────────────────
  "settings.title":              { en: "Settings",                   ur: "ترتیبات" },
  "settings.language":           { en: "Language",                   ur: "زبان" },
  "settings.language.desc":      { en: "Choose your preferred language for the interface", ur: "انٹرفیس کے لیے زبان منتخب کریں" },

  // ── Dashboard ─────────────────────────────────────────────────────────────
  "dash.Today Sales":       { en: "Today's Sales",    ur: "آج کی فروخت" },
  "dash.Total Revenue":     { en: "Total Revenue",    ur: "کل آمدنی" },
  "dash.Inventory":         { en: "Inventory Items",  ur: "اسٹاک آئٹمز" },
  "dash.Customers":         { en: "Customers",        ur: "گاہک" },
  "dash.Yesterday":         { en: "Yesterday",        ur: "کل" },
  "dash.This Week":         { en: "This Week",        ur: "اس ہفتے" },
  "dash.Last Week":         { en: "Last Week",        ur: "پچھلے ہفتے" },
  "dash.This Month":        { en: "This Month",       ur: "اس مہینے" },
  "dash.Last Month":        { en: "Last Month",       ur: "پچھلے مہینے" },
  "dash.This Year":         { en: "This Year",        ur: "اس سال" },
  "dash.Custom Range":      { en: "Custom Range",     ur: "اپنی تاریخ چنیں" },
  "dash.Sales from yesterday": { en: "Sales from yesterday", ur: "کل کی فروخت" },
  "dash.Mon to today":      { en: "Mon - today",      ur: "پیر سے آج تک" },
  "dash.Mon to Sun prev":   { en: "Mon - Sun, prev week", ur: "پیر سے اتوار، پچھلا ہفتہ" },
  "dash.Pick a date range": { en: "Pick a date range", ur: "تاریخ کی حد منتخب کریں" },
  "dash.Add Mobile":        { en: "Add Mobile",       ur: "موبائل شامل کریں" },
  "dash.Reports":           { en: "Reports",          ur: "رپورٹس" },
  "dash.Sales Revenue":     { en: "Sales Revenue",    ur: "فروخت کی آمدنی" },
  "dash.Purchases":         { en: "Purchases",        ur: "خریداری" },
  "dash.Gross Profit":      { en: "Gross Profit",     ur: "کل منافع" },
  "dash.Total Products":    { en: "Total Products",   ur: "کل پراڈکٹس" },
  "dash.Suppliers":         { en: "Suppliers",        ur: "سپلائرز" },
  "dash.Total Sales":       { en: "Total Sales",      ur: "کل فروخت" },
  "dash.transactions":      { en: "transactions",     ur: "لین دین" },
  "dash.orders":            { en: "orders",           ur: "آرڈرز" },
  "dash.margin":            { en: "margin",           ur: "منافع کی شرح" },
  "dash.Welcome back":      { en: "Welcome back,",    ur: "خوش آمدید," },
  "dash.Transactions":      { en: "Transactions",     ur: "لین دین" },

  // ── New Sale screen (app/sales/new/page.tsx) ────────────────────────────────
  "sale.Review Sale":            { en: "Review Sale",              ur: "فروخت کا جائزہ" },
  "sale.Cart Items":             { en: "Cart Items",                ur: "ٹوکری میں سامان" },
  "sale.Order Totals":           { en: "Order Totals",              ur: "کل حساب" },
  "sale.Discount Field":          { en: "Discount (Rs)",             ur: "رعایت (روپے)" },
  "sale.Tax Field":               { en: "Tax / Other (Rs)",          ur: "ٹیکس / دیگر (روپے)" },
  "sale.Subtotal":                { en: "Subtotal",                  ur: "ذیلی رقم" },
  "sale.Discount":                { en: "Discount",                  ur: "رعایت" },
  "sale.Tax":                     { en: "Tax",                       ur: "ٹیکس" },
  "sale.Grand Total":             { en: "Grand Total",               ur: "کل رقم" },
  "sale.Selling below cost":      { en: "Selling below cost:",       ur: "خرید سے کم قیمت پر فروخت:" },
  "sale.Payment - Select Accounts": { en: "Payment - Select Accounts", ur: "ادائیگی - اکاؤنٹ چنیں" },
  "sale.Select one or more accounts": { en: "Select one or more accounts", ur: "ایک یا زیادہ اکاؤنٹ چنیں" },
  "sale.No accounts":             { en: "No finance accounts found. Set up accounts in Finance first.", ur: "کوئی اکاؤنٹ نہیں ملا۔ پہلے مالیات میں اکاؤنٹ بنائیں۔" },
  "sale.Amount received via":     { en: "Amount received via",       ur: "رقم موصول ہوئی بذریعہ" },
  "sale.Total Received":          { en: "Total Received",            ur: "کل موصول شدہ رقم" },
  "sale.Change to Return":        { en: "Change to Return",          ur: "واپس کرنے والے پیسے" },
  "sale.Outstanding Balance":     { en: "Outstanding Balance",       ur: "باقی رقم" },
  "sale.due":                     { en: "due",                       ur: "باقی ہے" },
  "sale.Payment Status":          { en: "Payment Status:",           ur: "ادائیگی کی حیثیت:" },
  "sale.Paid in Full":            { en: "Paid in Full",              ur: "پوری ادائیگی" },
  "sale.Partial Payment":         { en: "Partial Payment",           ur: "کچھ ادائیگی" },
  "sale.Split across accounts":   { en: "Split across",              ur: "تقسیم شدہ بذریعہ" },
  "sale.accounts":                { en: "accounts",                  ur: "اکاؤنٹس" },
  "sale.Warranty":                { en: "Warranty",                  ur: "وارنٹی" },
  "sale.No Warranty":             { en: "No Warranty",               ur: "کوئی وارنٹی نہیں" },
  "sale.3 Days":                  { en: "3 Days",                    ur: "3 دن" },
  "sale.7 Days":                  { en: "7 Days",                    ur: "7 دن" },
  "sale.15 Days":                 { en: "15 Days",                   ur: "15 دن" },
  "sale.1 Month":                 { en: "1 Month",                   ur: "1 مہینہ" },
  "sale.3 Months":                { en: "3 Months",                  ur: "3 مہینے" },
  "sale.Notes placeholder":       { en: "e.g. customer requested gift wrap...", ur: "مثلاً گاہک نے گفٹ ریپ مانگا..." },
  "sale.Notes":                   { en: "Notes",                     ur: "نوٹس" },
  "sale.optional":                { en: "(optional)",                ur: "(اختیاری)" },
  "sale.Full payment required":   { en: "Full payment required for walk-in customers", ur: "واک اِن گاہک سے پوری رقم لینا ضروری ہے" },
  "sale.still unpaid":            { en: "still unpaid. Walk-in customers cannot carry outstanding balance.", ur: "ابھی باقی ہے۔ واک اِن گاہک پر بقایا رقم نہیں چھوڑی جا سکتی۔" },
  "sale.Complete Sale":           { en: "Complete Sale",             ur: "فروخت مکمل کریں" },
  "sale.Processing":              { en: "Processing...",             ur: "کارروائی جاری ہے..." },
  "sale.Walk-in Customer":        { en: "Walk-in Customer",          ur: "واک اِن گاہک" },
  "sale.each":                    { en: "each",                      ur: "فی عدد" },
  "sale.item types":              { en: "item type(s)",              ur: "قسم کا سامان" },

  // ── Sales list page (app/sales/page.tsx) ────────────────────────────────────
  "sale.list.New Sale":           { en: "New Sale",                  ur: "نئی فروخت" },
  "sale.list.Invoice":            { en: "Invoice",                   ur: "رسید نمبر" },
  "sale.list.Customer":           { en: "Customer",                  ur: "گاہک" },
  "sale.list.Date":               { en: "Date",                      ur: "تاریخ" },
  "sale.list.Items":              { en: "Items",                     ur: "سامان" },
  "sale.list.Total":              { en: "Total",                     ur: "کل رقم" },
  "sale.list.Payment":            { en: "Payment",                   ur: "ادائیگی" },
  "sale.list.View details":       { en: "View details",              ur: "تفصیلات دیکھیں" },
  "sale.list.Download invoice":   { en: "Download invoice PDF",      ur: "رسید ڈاؤن لوڈ کریں" },
  "sale.list.Process return":     { en: "Process return / refund",   ur: "واپسی / رقم واپسی کریں" },
  "sale.list.Status":             { en: "Status",                    ur: "حیثیت" },
  "sale.list.Actions":            { en: "Actions",                   ur: "کارروائی" },
  "sale.list.View":               { en: "View",                      ur: "دیکھیں" },
  "sale.list.Print":              { en: "Print",                     ur: "پرنٹ کریں" },
  "sale.list.Delete":             { en: "Delete",                    ur: "حذف کریں" },
  "sale.list.Delete confirm title": { en: "Delete this sale?",       ur: "کیا یہ فروخت حذف کرنی ہے؟" },
  "sale.list.Delete confirm desc": { en: "This will reverse stock, payments, and finance records for this sale. This cannot be undone.", ur: "اس سے اسٹاک، ادائیگی اور مالیاتی ریکارڈ واپس ہو جائیں گے۔ یہ واپس نہیں ہو سکتا۔" },
  "sale.list.Search":             { en: "Search invoice, customer...", ur: "رسید یا گاہک تلاش کریں..." },
  "sale.list.All Status":         { en: "All Status",                ur: "تمام حیثیت" },
  "sale.list.Total Revenue":      { en: "Total Revenue",             ur: "کل آمدنی" },
  "sale.list.No sales":           { en: "No sales yet",              ur: "ابھی تک کوئی فروخت نہیں" },
  "sale.list.No sales desc":      { en: "Sales you complete will show up here.", ur: "آپ کی مکمل کی گئی فروخت یہاں نظر آئے گی۔" },
  "sale.list.Page title":         { en: "Sales",                     ur: "فروخت" },
  "sale.list.Page desc":          { en: "Manage and track all sales transactions", ur: "تمام فروخت کا انتظام اور نگرانی کریں" },
  "sale.list.Export":             { en: "Export",                    ur: "برآمد کریں" },
  "sale.list.Today's Sales":      { en: "Today's Sales",             ur: "آج کی فروخت" },
  "sale.list.This Week":          { en: "This Week",                 ur: "اس ہفتے" },
  "sale.list.This Month":         { en: "This Month",                ur: "اس مہینے" },
  "sale.list.Outstanding":        { en: "Outstanding",               ur: "باقی رقم" },
  "sale.list.pending":            { en: "pending",                   ur: "زیر التواء" },
  "sale.list.Completion Rate":    { en: "Completion Rate",           ur: "تکمیل کی شرح" },
  "sale.list.completed":          { en: "completed",                 ur: "مکمل" },
  "sale.list.Collection Rate":    { en: "Collection Rate",           ur: "وصولی کی شرح" },
  "sale.list.collected":          { en: "collected",                 ur: "وصول شدہ" },
  "sale.list.Filters":            { en: "Filters",                   ur: "فلٹرز" },
  "sale.list.Universal search":   { en: "Search by invoice #, customer, IMEI, product name, price, color...", ur: "رسید نمبر، گاہک، آئی ایم ای آئی، پراڈکٹ، قیمت یا رنگ سے تلاش کریں..." },
  "sale.list.of":                 { en: "of",                        ur: "میں سے" },
  "sale.list.sales":              { en: "sales",                     ur: "فروخت" },
  "sale.list.Customer name":      { en: "Customer name...",          ur: "گاہک کا نام..." },
  "sale.list.Model Product":      { en: "Model / Product",           ur: "ماڈل / پراڈکٹ" },
  "sale.list.Model search":       { en: "e.g. iPhone 15, Samsung...", ur: "مثلاً آئی فون 15، سام سنگ..." },
  "sale.list.Sale Amount":        { en: "Sale Amount (Rs)",          ur: "فروخت کی رقم (روپے)" },
  "sale.list.Min":                { en: "Min",                       ur: "کم از کم" },
  "sale.list.Max":                { en: "Max",                       ur: "زیادہ سے زیادہ" },
  "sale.list.Date Range":         { en: "Date Range",                ur: "تاریخ کی حد" },
  "sale.list.All Methods":        { en: "All Methods",               ur: "تمام طریقے" },
  "sale.list.All Statuses":       { en: "All Statuses",              ur: "تمام حیثیت" },
  "sale.list.Reset":              { en: "Reset",                     ur: "دوبارہ ترتیب دیں" },
  "sale.list.No sales found":     { en: "No sales found",            ur: "کوئی فروخت نہیں ملی" },
  "sale.list.Udhaar":             { en: "Udhaar",                    ur: "ادھار" },
  "sale.list.PDF":                { en: "PDF",                       ur: "پی ڈی ایف" },
  "sale.list.Refund":             { en: "Refund",                    ur: "رقم واپسی" },
  "sale.list.item":               { en: "item",                      ur: "چیز" },
  "sale.list.items":              { en: "items",                     ur: "چیزیں" },
  "sale.list.Quick search":       { en: "Quick search...",           ur: "فوری تلاش..." },
  "sale.list.Delete Sale":        { en: "Delete Sale?",              ur: "کیا فروخت حذف کرنی ہے؟" },
  "sale.list.Delete desc":        { en: "This will permanently delete", ur: "یہ ہمیشہ کے لیے حذف کر دے گا" },
  "sale.list.Delete desc 2":      { en: "and reverse all inventory changes - phones return to in-stock, accessories stock restored, finance balances reversed. This cannot be undone.", ur: "اور تمام اسٹاک تبدیلیاں واپس ہو جائیں گی - فون دوبارہ اسٹاک میں آ جائیں گے، اضافی سامان کا اسٹاک بحال ہو جائے گا، اور مالیاتی حساب واپس ہو جائے گا۔ یہ واپس نہیں ہو سکتا۔" },
  "sale.list.Deleting":           { en: "Deleting...",               ur: "حذف ہو رہا ہے..." },

  // ── New Sale: success screen ─────────────────────────────────────────────
  "sale.Loading POS":             { en: "Loading POS...",            ur: "لوڈ ہو رہا ہے..." },
  "sale.Sale Complete":           { en: "Sale Complete!",            ur: "فروخت مکمل ہو گئی!" },
  "sale.Invoice":                 { en: "Invoice",                   ur: "رسید" },
  "sale.Customer Details":        { en: "Customer Details",          ur: "گاہک کی تفصیلات" },
  "sale.Name":                    { en: "Name",                      ur: "نام" },
  "sale.Phone":                   { en: "Phone",                     ur: "فون نمبر" },
  "sale.Order Summary":           { en: "Order Summary",              ur: "آرڈر کا خلاصہ" },
  "sale.Total":                   { en: "Total",                     ur: "کل رقم" },
  "sale.Amount Received":         { en: "Amount Received",           ur: "موصول شدہ رقم" },
  "sale.Change Returned":         { en: "Change Returned",           ur: "واپس کی گئی رقم" },
  "sale.Save PDF":                { en: "Save PDF",                  ur: "پی ڈی ایف محفوظ کریں" },
  "sale.Preview":                 { en: "Preview",                   ur: "پیش منظر" },
  "sale.New Sale Button":         { en: "+ New Sale",                ur: "+ نئی فروخت" },
  "sale.View All Sales":          { en: "View All Sales",            ur: "تمام فروخت دیکھیں" },
  "sale.Back":                    { en: "Back",                      ur: "واپس" },
  "sale.New Sale":                { en: "New Sale",                  ur: "نئی فروخت" },
  "sale.Review and Pay":          { en: "Review & Pay",              ur: "جائزہ اور ادائیگی" },
  "sale.Search placeholder":      { en: "Search by name, brand, IMEI, storage, color...", ur: "نام، برانڈ، آئی ایم ای آئی، میموری یا رنگ سے تلاش کریں..." },
  "sale.All":                     { en: "All",                       ur: "تمام" },
  "sale.Mobiles":                 { en: "Mobiles",                   ur: "موبائل فون" },
  "sale.Accessories":             { en: "Accessories",               ur: "اضافی سامان" },
  "sale.Used":                    { en: "Used",                      ur: "پرانے" },
  "sale.All Categories":          { en: "All Categories",            ur: "تمام اقسام" },
  "sale.Qty":                     { en: "Qty",                       ur: "تعداد" },
  "sale.CNIC placeholder":        { en: "CNIC",                      ur: "شناختی کارڈ نمبر" },
  "sale.Address placeholder":     { en: "Address",                   ur: "پتہ" },
  "sale.Already in cart":         { en: "Already in cart",           ur: "پہلے سے ٹوکری میں موجود ہے" },
  "sale.Add items first":         { en: "Add items to cart first",   ur: "پہلے ٹوکری میں سامان شامل کریں" },
  "sale.Select a customer":       { en: "Select a customer",         ur: "گاہک کا انتخاب کریں" },
  "sale.Name and phone required": { en: "Name and phone required",   ur: "نام اور فون نمبر ضروری ہیں" },
  "sale.Failed to create customer": { en: "Failed to create customer", ur: "گاہک شامل نہیں ہو سکا" },
  "sale.Failed to create sale":   { en: "Failed to create sale",     ur: "فروخت مکمل نہیں ہو سکی" },
  "sale.Full Name":               { en: "Full Name *",               ur: "پورا نام *" },
  "sale.Phone Field":             { en: "Phone *",                   ur: "فون نمبر *" },
  "sale.Credit Limit":            { en: "Credit Limit (Rs)",         ur: "قرض کی حد (روپے)" },
  "sale.Save Customer":           { en: "Save Customer",             ur: "گاہک محفوظ کریں" },
  "sale.Max stock reached":       { en: "Max stock reached",         ur: "زیادہ سے زیادہ اسٹاک ختم ہو گیا" },
  "sale.added":                   { en: "added",                     ur: "شامل ہو گیا" },
  "sale.Customer saved":          { en: "saved!",                    ur: "محفوظ ہو گیا!" },
  "sale.completed":               { en: "completed!",                ur: "مکمل ہو گئی!" },

  // ── Person Ledger (app/ledger/persons/page.tsx) ─────────────────────────────
  "ledger.person.Title":              { en: "Person Ledger",              ur: "ذاتی کھاتہ" },
  "ledger.person.Description":        { en: "Track money given to or taken from individuals", ur: "لوگوں کو دی یا لی گئی رقم کا حساب رکھیں" },
  "ledger.person.Money Out":          { en: "Money Out",                  ur: "رقم دی گئی" },
  "ledger.person.Money In":           { en: "Money In",                   ur: "رقم آئی" },
  "ledger.person.PDF":                { en: "PDF",                        ur: "پی ڈی ایف" },
  "ledger.person.Excel":              { en: "Excel",                      ur: "ایکسل" },
  "ledger.person.Select Person":      { en: "Select Person",              ur: "شخص منتخب کریں" },
  "ledger.person.All Persons":        { en: "All Persons",                ur: "تمام افراد" },
  "ledger.person.From Date":          { en: "From Date",                  ur: "تاریخ سے" },
  "ledger.person.To Date":            { en: "To Date",                    ur: "تاریخ تک" },
  "ledger.person.No persons":         { en: "No persons added yet. Go to", ur: "ابھی تک کوئی شخص شامل نہیں ہوا۔ لوگ شامل کرنے کے لیے" },
  "ledger.person.No persons link":    { en: "Persons",                    ur: "افراد" },
  "ledger.person.No persons suffix":  { en: "page to add people first.",  ur: "صفحے پر جائیں۔" },
  "ledger.person.Total Gave":         { en: "Total Gave",                 ur: "کل دی گئی رقم" },
  "ledger.person.Money we gave out":  { en: "Money we gave out",          ur: "ہم نے جو رقم دی" },
  "ledger.person.Total Took":         { en: "Total Took",                 ur: "کل لی گئی رقم" },
  "ledger.person.Money we received":  { en: "Money we received",          ur: "ہمیں جو رقم ملی" },
  "ledger.person.Net Balance":        { en: "Net Balance",                ur: "خالص بقایا" },
  "ledger.person.Closing Balance":    { en: "Closing Balance",            ur: "آخری بقایا" },
  "ledger.person.Date":               { en: "Date",                       ur: "تاریخ" },
  "ledger.person.Person":             { en: "Person",                     ur: "شخص" },
  "ledger.person.Description col":    { en: "Description",                ur: "تفصیل" },
  "ledger.person.Gave Dr":            { en: "Gave (Dr)",                  ur: "دی (ڈیبٹ)" },
  "ledger.person.Took Cr":            { en: "Took (Cr)",                  ur: "لی (کریڈٹ)" },
  "ledger.person.Balance":            { en: "Balance",                    ur: "بقایا" },
  "ledger.person.Totals":             { en: "Totals",                     ur: "کل میزان" },
  "ledger.person.No tx selected":     { en: "No transactions found. Click \"Add Transaction\" to record one.", ur: "کوئی لین دین نہیں ملا۔ ایک درج کرنے کے لیے \"لین دین شامل کریں\" پر کلک کریں۔" },
  "ledger.person.No tx period":       { en: "No transactions found for the selected period.", ur: "منتخب مدت کے لیے کوئی لین دین نہیں ملا۔" },
  "ledger.person.Add Transaction":    { en: "Add Transaction",            ur: "لین دین شامل کریں" },
  "ledger.person.Transaction Type":   { en: "Transaction Type",           ur: "لین دین کی قسم" },
  "ledger.person.Gave Money":         { en: "Gave Money",                 ur: "رقم دی" },
  "ledger.person.Took Money":         { en: "Took Money",                 ur: "رقم لی" },
  "ledger.person.Gave hint":          { en: "We gave money to them — their balance increases (Dr)", ur: "ہم نے انہیں رقم دی — ان کا بقایا بڑھ جائے گا" },
  "ledger.person.Took hint":          { en: "They gave money to us — their balance decreases (Cr)", ur: "انہوں نے ہمیں رقم دی — ان کا بقایا کم ہو جائے گا" },
  "ledger.person.Amount":             { en: "Amount (Rs)",                ur: "رقم (روپے)" },
  "ledger.person.Pay From Account":   { en: "Pay From Account",           ur: "کس اکاؤنٹ سے ادائیگی" },
  "ledger.person.Deposit to Account": { en: "Deposit to Account",         ur: "کس اکاؤنٹ میں جمع" },
  "ledger.person.Select account":     { en: "Select account",             ur: "اکاؤنٹ منتخب کریں" },
  "ledger.person.Payment Method":     { en: "Payment Method",             ur: "ادائیگی کا طریقہ" },
  "ledger.person.Notes":              { en: "Notes",                      ur: "نوٹس" },
  "ledger.person.Notes placeholder":  { en: "Optional description",       ur: "اختیاری تفصیل" },
  "ledger.person.Cancel":             { en: "Cancel",                     ur: "منسوخ" },
  "ledger.person.Saving":             { en: "Saving...",                  ur: "محفوظ ہو رہا ہے..." },
  "ledger.person.Record Gave":        { en: "Record Gave",                ur: "دی گئی رقم درج کریں" },
  "ledger.person.Record Took":        { en: "Record Took",                ur: "لی گئی رقم درج کریں" },
  "ledger.person.Opening Balance":    { en: "Opening Balance",            ur: "ابتدائی بقایا" },
  "ledger.person.Gave":               { en: "Gave",                       ur: "دی" },
  "ledger.person.Took":               { en: "Took",                       ur: "لی" },
  "ledger.person.Reference":          { en: "Reference",                  ur: "حوالہ نمبر" },
  "ledger.person.They need to pay us": { en: "They need to pay us",       ur: "انہیں ہمیں دینا ہے" },
  "ledger.person.We need to pay them": { en: "We need to pay them",       ur: "ہمیں انہیں دینا ہے" },
  "ledger.person.Settled":            { en: "Settled",                    ur: "حساب صاف" },
  "ledger.person.Account Statement":  { en: "Account Statement",          ur: "کھاتے کا بیان" },
  "ledger.person.All Persons Statement": { en: "All Persons",              ur: "تمام افراد" },
  "ledger.person.Bal":                { en: "Bal:",                       ur: "بقایا:" },
  "ledger.person.Dr":                 { en: "Dr",                         ur: "ڈیبٹ" },
  "ledger.person.Cr":                 { en: "Cr",                         ur: "کریڈٹ" },
  "ledger.person.Deleting":           { en: "Deleting...",                ur: "حذف ہو رہا ہے..." },
  "ledger.person.Delete Transaction": { en: "Delete Transaction",         ur: "لین دین حذف کریں" },
  "ledger.person.Delete desc suffix": { en: "transaction of",             ur: "لین دین بمقدار" },
  "ledger.person.Delete desc end":    { en: "This will also reverse the linked account balance.", ur: "یہ منسلک اکاؤنٹ کا بیلنس بھی واپس کر دے گا۔" },

  // ── Supplier Ledger (app/ledger/suppliers/page.tsx) ─────────────────────────
  "ledger.supplier.Title":            { en: "Supplier Ledger",            ur: "سپلائر کھاتہ" },
  "ledger.supplier.Description":      { en: "View financial records and outstanding payables for any supplier", ur: "کسی بھی سپلائر کا حساب اور واجب الادا رقم دیکھیں" },
  "ledger.supplier.Select Supplier":  { en: "Select Supplier",             ur: "سپلائر منتخب کریں" },
  "ledger.supplier.All Suppliers":    { en: "All Suppliers",               ur: "تمام سپلائرز" },
  "ledger.supplier.Opening Balance":  { en: "Opening Balance (Rs)",        ur: "ابتدائی بقایا (روپے)" },
  "ledger.supplier.Opening hint":     { en: "Positive = we need to pay them · Negative = we paid extra (advance)", ur: "مثبت = ہمیں ادا کرنا ہے · منفی = ہم نے زیادہ ادا کیا" },
  "ledger.supplier.Total Purchases":  { en: "Total Purchases",             ur: "کل خریداری" },
  "ledger.supplier.We bought":        { en: "Total we bought from supplier", ur: "سپلائر سے کل خریداری" },
  "ledger.supplier.Total Paid":       { en: "Total Paid",                  ur: "کل ادائیگی" },
  "ledger.supplier.Payments made":    { en: "Payments made to supplier",   ur: "سپلائر کو کی گئی ادائیگی" },
  "ledger.supplier.Outstanding":      { en: "Outstanding",                 ur: "باقی رقم" },
  "ledger.supplier.We need to pay":   { en: "We need to pay this supplier", ur: "ہمیں اس سپلائر کو دینا ہے" },
  "ledger.supplier.Account settled":  { en: "Account settled",             ur: "حساب صاف ہے" },
  "ledger.supplier.We paid extra":    { en: "We paid extra (advance)",     ur: "ہم نے زیادہ ادا کیا" },
  "ledger.supplier.Account Statement": { en: "Account Statement",          ur: "کھاتے کا بیان" },
  "ledger.supplier.Purchase Cr":      { en: "Purchase (Cr)",               ur: "خریداری (کریڈٹ)" },
  "ledger.supplier.Payment Dr":       { en: "Payment (Dr)",                ur: "ادائیگی (ڈیبٹ)" },
  "ledger.supplier.Rebate Dr":        { en: "Rebate (Dr)",                 ur: "ریبیٹ (ڈیبٹ)" },
  "ledger.supplier.Date":             { en: "Date",                        ur: "تاریخ" },
  "ledger.supplier.Reference":        { en: "Reference",                   ur: "حوالہ نمبر" },
  "ledger.supplier.Description col":  { en: "Description",                 ur: "تفصیل" },
  "ledger.supplier.Debit":            { en: "Debit",                       ur: "ڈیبٹ" },
  "ledger.supplier.Credit":           { en: "Credit",                      ur: "کریڈٹ" },
  "ledger.supplier.Balance":          { en: "Balance",                     ur: "بقایا" },
  "ledger.supplier.Partial":          { en: "Partial",                     ur: "کچھ ادا شدہ" },
  "ledger.supplier.Pay Supplier":     { en: "Pay Supplier",                ur: "سپلائر کو ادائیگی کریں" },
  "ledger.supplier.Amount":           { en: "Amount (Rs)",                 ur: "رقم (روپے)" },
  "ledger.supplier.Payment Account":  { en: "Payment Account",             ur: "ادائیگی کا اکاؤنٹ" },
  "ledger.supplier.Payment Method":   { en: "Payment Method",              ur: "ادائیگی کا طریقہ" },
  "ledger.supplier.Notes":            { en: "Notes",                       ur: "نوٹس" },
  "ledger.supplier.Cancel":           { en: "Cancel",                      ur: "منسوخ" },
  "ledger.supplier.Pay":              { en: "Pay",                         ur: "ادائیگی کریں" },
  "ledger.supplier.Paying":           { en: "Paying...",                   ur: "ادائیگی ہو رہی ہے..." },
  "ledger.supplier.No suppliers":     { en: "No suppliers found",          ur: "کوئی سپلائر نہیں ملا" },
  "ledger.supplier.PDF":              { en: "PDF",                         ur: "پی ڈی ایف" },
  "ledger.supplier.Excel":            { en: "Excel",                       ur: "ایکسل" },
  "ledger.supplier.Edit split":       { en: "Edit split",                  ur: "تقسیم تبدیل کریں" },
  "ledger.supplier.From Date":        { en: "From Date",                   ur: "تاریخ سے" },
  "ledger.supplier.To Date":          { en: "To Date",                     ur: "تاریخ تک" },
  "ledger.supplier.Clear selection":  { en: "Clear selection",             ur: "انتخاب ہٹائیں" },
  "ledger.supplier.Search placeholder": { en: "Search description, reference, supplier, date...", ur: "تفصیل، حوالہ نمبر، سپلائر یا تاریخ سے تلاش کریں..." },
  "ledger.supplier.No tx":            { en: "No transactions found for this supplier in the selected period.", ur: "منتخب مدت کے لیے اس سپلائر کا کوئی لین دین نہیں ملا۔" },
  "ledger.supplier.All Suppliers Statement": { en: "All Suppliers",        ur: "تمام سپلائرز" },
  "ledger.supplier.Dr":               { en: "Dr",                          ur: "ڈیبٹ" },
  "ledger.supplier.Cr":               { en: "Cr",                          ur: "کریڈٹ" },
  "ledger.supplier.Bal":              { en: "Bal:",                        ur: "بقایا:" },
  "ledger.supplier.Rebates":          { en: "Rebates / Rate Diff",         ur: "ریبیٹ / ریٹ فرق" },
  "ledger.supplier.Totals":           { en: "Totals",                      ur: "کل میزان" },
  "ledger.supplier.Supplier col":     { en: "Supplier",                    ur: "سپلائر" },
  "ledger.supplier.View details":     { en: "View details",                ur: "تفصیل دیکھیں" },
  "ledger.supplier.Paying to":        { en: "Paying to",                   ur: "ادائیگی کس کو" },
  "ledger.supplier.Outstanding balance": { en: "Outstanding balance",      ur: "واجب الادا رقم" },
  "ledger.supplier.Method":           { en: "Method",                      ur: "طریقہ" },
  "ledger.supplier.Select account":   { en: "Select account...",           ur: "اکاؤنٹ منتخب کریں..." },
  "ledger.supplier.Notes optional":   { en: "Notes (optional)",            ur: "نوٹس (اختیاری)" },
  "ledger.supplier.Notes placeholder": { en: "e.g. Cheque #1234, partial payment...", ur: "مثلاً چیک نمبر 1234، جزوی ادائیگی..." },
  "ledger.supplier.Recording":        { en: "Recording...",                ur: "درج ہو رہا ہے..." },
  "ledger.supplier.Record Payment":   { en: "Record Payment",              ur: "ادائیگی درج کریں" },
  "ledger.supplier.Purchase Transaction": { en: "Purchase Transaction",    ur: "خریداری کا لین دین" },
  "ledger.supplier.Payment Made":     { en: "Payment Made",                ur: "کی گئی ادائیگی" },
  "ledger.supplier.Rebate Credit":    { en: "Rebate Credit",               ur: "ریبیٹ کریڈٹ" },
  "ledger.supplier.Rate Difference Credit": { en: "Rate Difference Credit", ur: "ریٹ فرق کریڈٹ" },
  "ledger.supplier.Purchase Value":   { en: "Purchase Value",              ur: "خریداری کی رقم" },
  "ledger.supplier.Paid at Purchase": { en: "Paid at Purchase",            ur: "خریداری پر ادا شدہ" },
  "ledger.supplier.Rebate Credit reduces": { en: "Rebate Credit (reduces payable)", ur: "ریبیٹ کریڈٹ (واجب الادا کم کرتا ہے)" },
  "ledger.supplier.Debit Dr":         { en: "Debit (Dr)",                  ur: "ڈیبٹ" },
  "ledger.supplier.Net Due Cr":       { en: "Net Due (Cr)",                ur: "خالص واجب الادا" },
  "ledger.supplier.Credit Cr":        { en: "Credit (Cr)",                 ur: "کریڈٹ" },
  "ledger.supplier.Running Balance":  { en: "Running Balance",             ur: "چلتا بقایا" },
  "ledger.supplier.Payment Status":   { en: "Payment Status",              ur: "ادائیگی کی حیثیت" },
  "ledger.supplier.Fully Paid":       { en: "Fully Paid",                  ur: "پوری ادائیگی" },
  "ledger.supplier.Supplier":         { en: "Supplier",                    ur: "سپلائر" },
  "ledger.supplier.Rebate Details":   { en: "Rebate Details",              ur: "ریبیٹ کی تفصیل" },
  "ledger.supplier.Model":            { en: "Model",                       ur: "ماڈل" },
  "ledger.supplier.Units":            { en: "Units",                       ur: "یونٹس" },
  "ledger.supplier.Rate per Unit":    { en: "Rate / Unit",                 ur: "ریٹ / یونٹ" },
  "ledger.supplier.Total Credit":     { en: "Total Credit",                ur: "کل کریڈٹ" },
  "ledger.supplier.Entry Type":       { en: "Entry Type",                  ur: "اندراج کی قسم" },

  // ── Customer Ledger (app/ledger/customers/page.tsx) ─────────────────────────
  "ledger.customer.Title":            { en: "Customer Ledger",             ur: "گاہک کھاتہ" },
  "ledger.customer.Description":      { en: "Account statements, outstanding dues, advances and settled accounts", ur: "کھاتے کا بیان، باقی رقم، ایڈوانس اور صاف شدہ حساب" },
  "ledger.customer.Collect Payment":  { en: "Collect Payment",             ur: "ادائیگی وصول کریں" },
  "ledger.customer.PDF":              { en: "PDF",                         ur: "پی ڈی ایف" },
  "ledger.customer.Excel":            { en: "Excel",                       ur: "ایکسل" },
  "ledger.customer.Customer":         { en: "Customer",                    ur: "گاہک" },
  "ledger.customer.All Customers":    { en: "All Customers",               ur: "تمام گاہک" },
  "ledger.customer.Due":              { en: "Due Rs",                      ur: "باقی روپے" },
  "ledger.customer.Advance":          { en: "Advance",                     ur: "ایڈوانس" },
  "ledger.customer.Settled":          { en: "Settled",                     ur: "حساب صاف" },
  "ledger.customer.Account Status":   { en: "Account Status",              ur: "کھاتے کی حیثیت" },
  "ledger.customer.All Accounts":     { en: "All Accounts",                ur: "تمام کھاتے" },
  "ledger.customer.Outstanding Only": { en: "Outstanding / Dues Only",     ur: "صرف باقی رقم" },
  "ledger.customer.Cleared Only":     { en: "Settled / Cleared Only",      ur: "صرف صاف شدہ" },
  "ledger.customer.Advance Only":     { en: "Advance / Overpaid Only",     ur: "صرف ایڈوانس" },
  "ledger.customer.Period":           { en: "Period",                      ur: "مدت" },
  "ledger.customer.All Time":         { en: "All Time",                    ur: "تمام وقت" },
  "ledger.customer.This Week":        { en: "This Week",                   ur: "اس ہفتے" },
  "ledger.customer.Last Week":        { en: "Last Week",                   ur: "پچھلے ہفتے" },
  "ledger.customer.This Month":       { en: "This Month",                  ur: "اس مہینے" },
  "ledger.customer.Last Month":       { en: "Last Month",                  ur: "پچھلے مہینے" },
  "ledger.customer.This Quarter":     { en: "This Quarter",                ur: "اس سہ ماہی" },
  "ledger.customer.This Year":        { en: "This Year",                   ur: "اس سال" },
  "ledger.customer.Custom Range":     { en: "Custom Range",                ur: "اپنی تاریخ چنیں" },
  "ledger.customer.From Date":        { en: "From Date",                   ur: "تاریخ سے" },
  "ledger.customer.To Date":          { en: "To Date",                     ur: "تاریخ تک" },
  "ledger.customer.Opening Balance":  { en: "Opening Balance (Rs)",        ur: "ابتدائی بقایا (روپے)" },
  "ledger.customer.Opening hint":     { en: "0 (positive = customer needs to pay us, negative = advance paid)", ur: "0 (مثبت = گاہک نے ہمیں دینا ہے، منفی = ایڈوانس ادا کیا)" },
  "ledger.customer.Clear all filters": { en: "Clear all filters",          ur: "تمام فلٹر ہٹائیں" },
  "ledger.customer.Total Debit":      { en: "Total Debit",                 ur: "کل ڈیبٹ" },
  "ledger.customer.Charged to customer": { en: "Charged to customer",      ur: "گاہک سے وصول کرنا ہے" },
  "ledger.customer.Total Credit":     { en: "Total Credit",                ur: "کل کریڈٹ" },
  "ledger.customer.Payments received": { en: "Payments received",         ur: "موصول شدہ ادائیگی" },
  "ledger.customer.Net Balance":      { en: "Net Balance",                 ur: "خالص بقایا" },
  "ledger.customer.Customer still needs to pay": { en: "Customer still needs to pay", ur: "گاہک کو ابھی ادا کرنا ہے" },
  "ledger.customer.Customer paid extra": { en: "Customer paid extra (advance)", ur: "گاہک نے زیادہ ادا کیا (ایڈوانس)" },
  "ledger.customer.Status":           { en: "Status",                      ur: "حیثیت" },
  "ledger.customer.Outstanding Due":  { en: "Outstanding Due",             ur: "باقی رقم" },
  "ledger.customer.Advance Overpaid": { en: "Advance / Overpaid",          ur: "ایڈوانس / زیادہ ادا شدہ" },
  "ledger.customer.Account Settled":  { en: "Account Settled",             ur: "حساب صاف" },
  "ledger.customer.No tx filters":    { en: "No transactions found for the selected filters.", ur: "منتخب فلٹرز کے لیے کوئی لین دین نہیں ملا۔" },
  "ledger.customer.Try changing":     { en: "Try changing the date range or account status filter.", ur: "تاریخ کی حد یا کھاتے کی حیثیت کا فلٹر تبدیل کر کے دیکھیں۔" },
  "ledger.customer.Account Statement": { en: "Account Statement",          ur: "کھاتے کا بیان" },
  "ledger.customer.All Customers Statement": { en: "All Customers",        ur: "تمام گاہک" },
  "ledger.customer.Start":            { en: "Start",                       ur: "شروع" },
  "ledger.customer.Now":              { en: "Now",                        ur: "ابھی" },
  "ledger.customer.Sale Dr":          { en: "Sale (Dr)",                   ur: "فروخت (ڈیبٹ)" },
  "ledger.customer.Payment Cr":       { en: "Payment (Cr)",                ur: "ادائیگی (کریڈٹ)" },
  "ledger.customer.Date":             { en: "Date",                        ur: "تاریخ" },
  "ledger.customer.Reference":        { en: "Reference",                  ur: "حوالہ نمبر" },
  "ledger.customer.Description col":  { en: "Description",                 ur: "تفصیل" },
  "ledger.customer.Debit":            { en: "Debit",                       ur: "ڈیبٹ" },
  "ledger.customer.Credit":           { en: "Credit",                      ur: "کریڈٹ" },
  "ledger.customer.Balance":          { en: "Balance",                     ur: "بقایا" },
  "ledger.customer.Totals":           { en: "Totals",                      ur: "کل میزان" },
  "ledger.customer.Dr":               { en: "Dr",                          ur: "ڈیبٹ" },
  "ledger.customer.Cr":               { en: "Cr",                          ur: "کریڈٹ" },
  "ledger.customer.of":               { en: "of",                          ur: "میں سے" },
  "ledger.customer.Sale Details":     { en: "Sale Details",                ur: "فروخت کی تفصیل" },
  "ledger.customer.Payment Details":  { en: "Payment Details",             ur: "ادائیگی کی تفصیل" },
  "ledger.customer.Payment Method meta": { en: "Payment Method",           ur: "ادائیگی کا طریقہ" },
  "ledger.customer.Notes":            { en: "Notes",                       ur: "نوٹس" },
  "ledger.customer.Paid in Full":     { en: "Paid in Full",                ur: "پوری ادائیگی" },
  "ledger.customer.Partial Payment":  { en: "Partial Payment",             ur: "کچھ ادائیگی" },
  "ledger.customer.Payment Received": { en: "Payment Received",           ur: "ادائیگی موصول ہوئی" },
  "ledger.customer.Items Sold":       { en: "Items Sold",                  ur: "فروخت شدہ سامان" },
  "ledger.customer.Product":          { en: "Product",                     ur: "پراڈکٹ" },
  "ledger.customer.Type":             { en: "Type",                        ur: "قسم" },
  "ledger.customer.Qty":              { en: "Qty",                         ur: "تعداد" },
  "ledger.customer.Unit Price":       { en: "Unit Price",                  ur: "فی یونٹ قیمت" },
  "ledger.customer.Total":            { en: "Total",                       ur: "کل رقم" },
  "ledger.customer.IMEI":             { en: "IMEI:",                       ur: "آئی ایم ای آئی:" },
  "ledger.customer.Disc":             { en: "Disc:",                       ur: "رعایت:" },
  "ledger.customer.Subtotal":         { en: "Subtotal",                    ur: "ذیلی رقم" },
  "ledger.customer.Discount":         { en: "Discount",                    ur: "رعایت" },
  "ledger.customer.Amount Received":  { en: "Amount Received",             ur: "موصول شدہ رقم" },
  "ledger.customer.Balance Due":      { en: "Balance Due",                 ur: "باقی رقم" },
  "ledger.customer.Payment Info":     { en: "Payment Info",                ur: "ادائیگی کی معلومات" },
  "ledger.customer.Amount":           { en: "Amount",                      ur: "رقم" },
  "ledger.customer.Method":           { en: "Method",                      ur: "طریقہ" },
  "ledger.customer.record a payment": { en: "record a payment received",  ur: "موصول شدہ ادائیگی درج کریں" },
  "ledger.customer.Running Balance Due": { en: "Running Balance (Due)",   ur: "چلتا بقایا (واجب الادا)" },
  "ledger.customer.Advance on Account": { en: "Advance on Account",       ur: "کھاتے میں ایڈوانس" },
  "ledger.customer.After Collection": { en: "After Collection",           ur: "وصولی کے بعد" },
  "ledger.customer.Cr Settled":       { en: "Cr / Settled",               ur: "کریڈٹ / صاف" },
  "ledger.customer.Amount Received Field": { en: "Amount Received (Rs)",  ur: "موصول شدہ رقم (روپے)" },
  "ledger.customer.Enter amount":     { en: "Enter amount",                ur: "رقم درج کریں" },
  "ledger.customer.Payment Method Field": { en: "Payment Method",         ur: "ادائیگی کا طریقہ" },
  "ledger.customer.Deposit Account":  { en: "Deposit to Account",          ur: "کس اکاؤنٹ میں جمع" },
  "ledger.customer.Select account":  { en: "Select account",              ur: "اکاؤنٹ منتخب کریں" },
  "ledger.customer.Saving":           { en: "Saving...",                   ur: "محفوظ ہو رہا ہے..." },
  "ledger.customer.Collect":          { en: "Collect",                     ur: "وصول کریں" },
} as const

export type TranslationKey = keyof typeof translations

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------
interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  /** Looks up key in the dictionary. If the key doesn't exist at all, returns
   *  `fallback` (defaults to the key itself) instead of the raw key string -
   *  matters for callers that build keys dynamically, e.g. `status.${status}`
   *  for a status that hasn't been added to the dictionary yet. */
  t: (key: TranslationKey, fallback?: string) => string
  isRTL: boolean
}

const LanguageContext = createContext<LanguageContextType | null>(null)

const STORAGE_KEY = "mobitrack_language"

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY) as Language | null
      if (saved === "en" || saved === "ur") setLanguageState(saved)
    } catch {}
    setMounted(true)
  }, [])

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang)
    try { localStorage.setItem(STORAGE_KEY, lang) } catch {}
  }, [])

  const activeLang = mounted ? language : "en"

  const t = useCallback((key: TranslationKey, fallback?: string): string => {
    const entry = translations[key]
    if (!entry) return fallback ?? key
    return entry[activeLang] ?? entry.en
  }, [activeLang])

  const isRTL = false // Layout always stays LTR — only specific terms are translated

  return (
    <LanguageContext.Provider value={{ language: activeLang, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage(): LanguageContextType {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider")
  return ctx
}
